export { HomePage } from "./home"
export { LoginPage } from "./profile/login"
export { RegisterPage } from "./register"
export { ForgotPage } from "./forgotPassword"
export { ResetPasswordPage } from "./resetPassword"
export { ProfilePage } from "./profile"
export {AddRidePage} from "./addRide"